- name: Setup mysql repos
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disbale default mysql 8
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install mysql server 5.7
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Enable and start mysql
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Set mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
  ignore_errors: yes
    