components:
  - {name: cart, service_name: cart}
  - {name: catalogue, service_name: catalogue}
  - {name: frontend, service_name: nginx}
  - {name: user, service_name: user}
  - {name: shipping, service_name: shipping}
  - {name: payment, service_name: payment}
  
alert_files:
  - servicedown-alerts.yml
  - alerts.yml