- name: Download prometheus node exporter
  ansible.builtin.unarchive: 
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

  
- name: copy systemd exporter
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: restart exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: yes