- name: update prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alerts config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files}}"


- name: restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: chaeck prometheus is started
  ansible.builtin.shell: netstat -lntp | grep 9090

- name: update alertmanager config
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: restart alertmanager server
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: check alertmanager is started
  ansible.builtin.shell: netstat -lntp | grep 9093
 