- name: update prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alerts config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop:
  - servicedown-alerts.yml
  - alerts.yml

- name: restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
 