- name: Add Application user
  ansible.builtin.user:
    user: roboshop

- name: Delete application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application Directory
  ansible.builtin.file:
    path: /app
    state: directory

# Download from S3
#- name: Download and extract the {{component}} content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

 # Download from Nexus
- name: Download and extract the {{component}} content
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@nexus.devopsb71.tech:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes

#create nexus dns record and use it here
#credentials can give infront of url to authenticate nexus
#app_version will fetch from defaults folder of every component
