    # if [ "${schema_type}" == "mongo" ]; then
    #     print_head "copy mongodb repo file server"
    #     cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>${log_file}
    #     status_check $?
    #     print_head "install mongodb"
    #     yum install mongodb-org-shell -y &>>${log_file}
    #     status_check $?
    #     print_head "Load the schema"
    #     mongo --host mongodb.devopsb71.tech </app/schema/${component}.js &>>${log_file}
    #     status_check $?
    # elif [ "${schema_type} "== "mysql" ]; then
    #     print_head "Install mysql client"
    #     yum install mysql -y &>>${log_file}
    #     status_check $?

    #     print_head "Load schema"
    #     mysql -h mysql.devopsb71.tech -uroot -p${mysql_root_password} </app/schema/${component}.sql &>>${log_file}
    #     status_check $?

