groups:
- name: roboshop service alerts
  rules:
  {% for component in components %}
  
  - alert: service down alert - {{ item }} service
    expr: node_systemd_unit_state{exported_name="{{ item }}.service", state="active"}
    for: 30s
    labels:
      severity: critical
      application: {{ item }}
    annotations:
      summary: service down on cart server- service name- {{ item }}.service
  {% endfor %}