groups:
- name: roboshop service alerts
  rules:
  {% for component in components %}

  - alert: service down alert - {{ component }} service
    expr: node_systemd_unit_state{exported_name="{{ component }}.service", state="active"}
    for: 30s
    labels:
      severity: critical
      application: {{ component }}
    annotations:
      summary: service down on cart server- service name- {{ component }}.service
  {% endfor %}